// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfY5KyY33Vi_9lv4LvIcsbCC908Vhoi5Q',
    appId: '1:735267677154:web:a2d221509fa92ba5f84fbb',
    messagingSenderId: '735267677154',
    projectId: 'shopsmart-968fc',
    authDomain: 'shopsmart-968fc.firebaseapp.com',
    storageBucket: 'shopsmart-968fc.appspot.com',
    measurementId: 'G-DN8874XF4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr5T-RIECGJsr_weeHkQSp4e90g3HSn0o',
    appId: '1:735267677154:android:fbd51527099c4f13f84fbb',
    messagingSenderId: '735267677154',
    projectId: 'shopsmart-968fc',
    storageBucket: 'shopsmart-968fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa23gzCk8Hic8npQXr9PmkWz_2zu-wPwI',
    appId: '1:735267677154:ios:3f8e1cbf30f87c46f84fbb',
    messagingSenderId: '735267677154',
    projectId: 'shopsmart-968fc',
    storageBucket: 'shopsmart-968fc.appspot.com',
    iosClientId: '735267677154-32a9mmfde6rju4h9ers2h1rq2jl4n372.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa23gzCk8Hic8npQXr9PmkWz_2zu-wPwI',
    appId: '1:735267677154:ios:31f932d1eba9da20f84fbb',
    messagingSenderId: '735267677154',
    projectId: 'shopsmart-968fc',
    storageBucket: 'shopsmart-968fc.appspot.com',
    iosClientId: '735267677154-beqvslp6hbfsg69cmscu5nvbhbpei6n7.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopSmart.RunnerTests',
  );
}
